### ISSUE TITLE
v1 checklist

### ISSUE THREAD

**Issue by smikhalevski** [smikhalevski/jtdc#1]
- [ ] Use enum types in discriminated union validators;
- [ ] Use enum types in enum validators;
- [ ] Render `is{DiscriminatedUnion}{MappingKey}` type guards;
- [ ] Reuse variables in validators;
- [ ] Generate `index.ts` in each directory;
